version: '3.8'
services:
  db-mysql-fti-container:
    container_name: db-mysql-fti-container
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    #   - '${PORT_DATABASE}:3306'
    volumes:
      - ./mysql_data/:/var/lib/mysql # Adicionar em DockerIgnore

    networks:
      - nw_fti
  nest-api-fti-container:
    container_name: nest-api-fti-container
    build: .
    working_dir: ${PATH_API}
    env_file:
      - .env
    command: "yarn auto:prod"
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      # - ./dist/:/usr/src/api-node-fti/dist/ Verificar pois o dist é enviado vazio - Luan
      - ./package.json:${PATH_API}/package.json
      # - ./nest-cli.json:/usr/src/api-node-fti/nest-cli.json 
      # - ./prisma:/usr/src/api-node-fti/prisma/
    networks:
      - nw_fti   
networks:
  nw_fti:
    driver: bridge