name: CI

on:
  push:
    branches: [ release ]

  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
   
     - name: Setup NodeJs
       uses: actions/setup-node@v2
       with:
        node-version: 16.x
        
     - uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: ". , !node_modules"
        target: "projetos/nest-api-fti"
   
     - name: Update API   
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script:
         cd /home/app/projetos/nest-api-fti && docker-compose up -d
